### PR TITLE
fix: hybrid glossary tutorial region tag

### PR DESCRIPTION
**Pull request by leahecole**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/{{metadata['repo']['name']}}/issues) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by leahecole** [comment]
@bcoe any brilliant ideas as to why this timeout keeps happening? I didn't change anything related to that test

**Comment by bcoe** [comment]
@leahecole to me this seems like an issue with gRPC-js, might be worth looping in @alexander-fenster.

**Comment by alexander-fenster** [comment]
For me it looks like a real timeout happens elsewhere - maybe when working with GCS bucket. Does it repro locally?

**Comment by bcoe** [comment]
@alexander-fenster testing locally, running the sample seems to hang indefinitely on the line where we `await` the `operation.promise()`.

**Comment by alexander-fenster** [comment]
I will try it locally and see what happens.

**Comment by leahecole** [comment]
Keep me posted, @alexander-fenster! I can run it locally successfully. If you want to debug together or show me whatever magic you're trying, feel free to send me a calendar invite

**Pull request merged**
