### PR TITLE
fix(samples): use us-central1 region (not global)

### PR DESCRIPTION
**Pull request by beccasaurus**
Fixes an internally filed issue. [*](b/130803258)

### CODE REVIEW

**Comment by beccasaurus** [comment]
Not sure if this is `fix(samples)` or `docs(samples)` ~ I'll change the message to the correct syntax on squash and merge.

**Comment by leahecole** [comment]
Looks like the header might be wrong too - it probably has commas in the copyright line, which the bot does not like

**Comment by beccasaurus** [comment]
Can anyone recommend a commit message that meets the conventions? Or point me in the right direction?

Screen Shot 2019-08-29 at 3 52 19 PM

**Comment by stephenplusplus** [comment]
I think you just need to make "Use" -> "use".

**Comment by bcoe** [comment]
@stephenplusplus @beccasaurus I used an off the shelf linter that's a bit stricter than I'd like to be, I'll fix this:

https://github.com/googleapis/repo-automation-bots/issues/58
https://github.com/googleapis/repo-automation-bots/issues/59

**Pull request merged**
