### PR TITLE
Translate v3 readme

### PR DESCRIPTION
**Pull request by leahecole**
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by jkwlui** [comment]
@bcoe can you help look here? Did we have a way to add custom content to `README.md` without it being wiped out by autosynth?

**Comment by bcoe** [comment]
@jkwlui @leahecole :wave: we auto-generate the samples README now, but we can still give you the flexibility you need. Rather than manually editing `samples/README.md`, you can add the following header somewhere in each of your sample files:

```
// sample-metadata:
//   title: Metadata Example 2
//   description: this is a description.
//   usage: node goodnight-moon.js
```

You then simply run `synthtool` inside the repo, and it will pull in that meta information and provide it for each of your samples in the README.

If you need more room for customization, let me know, and we can add an additional partial that allows you to display custom information at the top of the sample README.

**Comment by leahecole** [comment]
Got it - thanks @bcoe  - i'll take a look on my bus ride home today.

**Comment by bcoe** [comment]
Leah and I are going to pair on the synthtool automation stuff later in the week (good chance to share knowledge).

**Comment by bcoe** [comment]
closing in favor of https://github.com/googleapis/nodejs-translate/pull/268

**Pull request closed without merging**
