### PR TITLE
docs(samples): Translate with automl model sample

### PR DESCRIPTION
**Pull request by leahecole**
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
This looks great.  @callmehiphop @leahecole can y'all look into the failing sample tests though?

**Comment by callmehiphop** [comment]
@JustinBeckwith looks like the test in question is the one being introduced in this PR?

**Comment by leahecole** [comment]
Taking a look now

**Comment by leahecole** [comment]
I think this previously had a .skip on it, and @beccasaurus and I decided it wasn't going to be fixed. Shall I re-add the .skip so kokoro can be happy?

**Comment by beccasaurus** [comment]
If it's possible to have a working test, I propose a working test. I haven't had a chance to TAL closely

**Comment by leahecole** [comment]
@beccasaurus I believe we decided that it was not easily possible to do so. I'll defer to your judgement, but previously we decided not to spend time on this.

**Comment by JustinBeckwith** [comment]
If we have no reasonable path forward for a test, I suggest we add a TODO in the test file, then just delete the bogus test.

**Comment by leahecole** [comment]
@JustinBeckwith TAL and let me know what you think - your approval is old so I don't want to merge yet if this doesn't fit your vision. I added a skip and a dummy AutoML model along with a TODO comment about what would be needed for a valid test.

**Pull request merged**
