### PR TITLE
feat: Use small request dependency

### PR DESCRIPTION
**Pull request by fhinkel**
Pass `teeny-request` to `common.Service` so we don't rely on
`request`.

### CODE REVIEW

**Comment by fhinkel** [comment]
Looks like `npm` from Node 6 can't install dependencies from branches the way it's specified.

**Comment by fhinkel** [comment]
I wrote `teeny-request` which we can use instead of `request`. My idea is that the client libraries pass `teeny-request` (or `request` if needed) to `nodejs-common`.

In the future, `nodejs-common` won't depend on `request` but use whatever is passed into it.

`teeny-request` has everything we need for `nodejs-translate`. I'll work through the other client libraries and add the functionality we need, or publish something like `teeny-request-streams` and so on. 

I haven't worked through `google-auth-library` yet.

**Comment by JustinBeckwith** [comment]
I love the idea, and I love the way that we could upgrade one package at a time to reduce risk.  A few thoughts/concerns:
- This wouldn't actually get rid of the dependency on request in the common, right?  I'm thinking this would just end up with having no impact on the actual loading time of the module since we're still going to end up loading request in other places in common.
- Scenario coverage.  I'm a little worried about the things we don't think about that request just does for us nicely.  Like proxies - I totally missed that when adopting axios.  Makes me wonder what else we're missing?  Do you have any ideas on how we could release something like this slowly to make sure we're not breaking folks?

**Comment by fhinkel** [comment]
This would get rid of request in common.

**Comment by fhinkel** [comment]
By default, libraries will use `teeny-request`, if users want more advanced options like proxies, they have to provide their own module, like `request`.

**Comment by JustinBeckwith** [comment]
Got it! It's awesome that this helps us dump request.  On the users providing their own advanced request library....  this makes me kinda nervous.  We're now basically saying that the request interface is a part of our API design.  While it's nice that we're not tied down to a single request library, it *does* mean that we're exposing an interface that will be used for all HTTP requests.  

I'm having trouble imagining that many users will want to BYO HTTP library when using our higher level libs.  It feels like we're leaking implementation details.  

Instead of making this super open ended - could we just control the use of teeny-request vs regular-request via an env var, similar to what we're doing in grpc?  That way we could roll this out *today*, and let customers start trying it with the new env vars.  Realistically - do we think we will have 2 options for the transport layer (regular request, teeny request) or (n) options?

**Comment by fhinkel** [comment]
If we're providing *all* options that `request` offers, we'll end up with an equally large module. I want to provide a small module by default, with limited options. Users that need special options would need to use `request`. 

Some libraries like `nodejs-translate` won't have the option to pass in a request module, because all it's uses are internal. 

Other libraries currently expose `request`, or `request.option` to the user. I don't want to break the API, so we need to keep doing that. 

Let's chat later in person!

**Comment by fhinkel** [comment]
Fixes: https://github.com/googleapis/nodejs-translate/pull/99

**Comment by fhinkel** [comment]
Before with `request`: 160 ms
selection_022

With `teeny-request`: 90 ms
selection_021

**Comment by JustinBeckwith** [comment]
Is the plan to release this and treat translate as the canary in the coal mine?  🐦

**Comment by fhinkel** [comment]
The bird is already singing: https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/pull/283 
But yes, probably better to get feedback earlier instead of breaking all libraries at once 🙈

**Pull request merged**
