### PR TITLE
doc: use new import syntax in samples

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by ofrobots** [comment]
This needs to be clearly marked as semver-major.

**Comment by JustinBeckwith** [comment]
Aside from the label, should we mark it any other way?

**Comment by JustinBeckwith** [comment]
Oh yeah!  Turns out I documented it there too :)
https://github.com/googleapis/nodejs-translate/pull/63

**Comment by ofrobots** [comment]
So this is actually NOT semver major?

**Comment by JustinBeckwith** [comment]
You are correct.  Sorry for the confusion.  I updated the PR title, and dropped the breaking change / semver label.

**Pull request merged**
